### ISSUE TITLE
definition of RMSE in wiki vs metrics

### ISSUE THREAD

**Issue by gschramm** [SyneRBI/PETRIC#90]
I think it is slightly confusing that the wiki says:
```
RMSE / mean(BG) should be < 0.01
```

but the corresponding metric in tensorboard
is called:
```
RMSE
```

Technically, the definition of the wiki is correct (and could be called "normalized RMSE or NRMSE").
But I understand that changing the metric names in tensorboard is probably not trivial anymore.

However, it should be clear that the RMSE shown in tensorboard is `RMSE / mean(BG)` and should be < 0.01.

**Comment by KrisThielemans** [comment]
Agreed. We didn't call it NMRSE because people then might expect we normalise by the mean of the VOI (as opposed to mean(BG), but the current situation is not clear.

I'm not sure what the consequences would be of renaming the TensorBoard metrics. @casperdcl can probably comment on that. If we can still change it, I suggest we
- modify the wiki to say "whole object normalised RMSE (nRMSE): blabla" and same for background
- use nRSME in the code.

**Comment by gschramm** [comment]
I think having a note / screenshot of tensorboard in the wiki and clearly saying that
"tensorboard AEM" must be < 0.005 and "tensorboard RMSE" < 0.01 should remove
the confusion.

**Comment by casperdcl** [comment]
updated https://github.com/SyneRBI/PETRIC/wiki#metrics-and-thresholds - better now?

**Comment by KrisThielemans** [comment]
looks good to me. @gschramm if you agree, can you close the issue?

**Comment by gschramm** [comment]
Thanks. Crystal clear now
